version: "3"

services:
    gofilm:
        build: .
        restart: "no"
        ports:
            - 8000:8000

    mysql-gofilm:
        image: mariadb:10.1
        hostname: mysql.docker
        command: --init-file /app/app/config/init.sql
        volumes:
            - ./init.sql:/app/app/config/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_DATABASE: gofilm
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
        ports:
            - 3336:3306
        restart: "no"