// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	carts "gofilm/bussinesses/carts"

	mock "github.com/stretchr/testify/mock"
)

// CartUseCase is an autogenerated mock type for the CartUseCase type
type CartUseCase struct {
	mock.Mock
}

// ChangeStatus provides a mock function with given fields: cartID
func (_m *CartUseCase) ChangeStatus(cartID int) error {
	ret := _m.Called(cartID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(cartID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCartUser provides a mock function with given fields: cart
func (_m *CartUseCase) CreateCartUser(cart *carts.Convert) (*carts.Cart, error) {
	ret := _m.Called(cart)

	var r0 *carts.Cart
	if rf, ok := ret.Get(0).(func(*carts.Convert) *carts.Cart); ok {
		r0 = rf(cart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carts.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*carts.Convert) error); ok {
		r1 = rf(cart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCartUser provides a mock function with given fields: userID
func (_m *CartUseCase) DeleteCartUser(userID int) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCartByID provides a mock function with given fields: id
func (_m *CartUseCase) GetCartByID(id int) (*carts.Cart, error) {
	ret := _m.Called(id)

	var r0 *carts.Cart
	if rf, ok := ret.Get(0).(func(int) *carts.Cart); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carts.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartByUser provides a mock function with given fields: userID
func (_m *CartUseCase) GetCartByUser(userID int) (*carts.Cart, error) {
	ret := _m.Called(userID)

	var r0 *carts.Cart
	if rf, ok := ret.Get(0).(func(int) *carts.Cart); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carts.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFilmUser provides a mock function with given fields: id
func (_m *CartUseCase) GetFilmUser(id int) (*carts.Cart, error) {
	ret := _m.Called(id)

	var r0 *carts.Cart
	if rf, ok := ret.Get(0).(func(int) *carts.Cart); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carts.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCartUser provides a mock function with given fields: userID, cart
func (_m *CartUseCase) UpdateCartUser(userID int, cart *carts.Cart) (*carts.Cart, error) {
	ret := _m.Called(userID, cart)

	var r0 *carts.Cart
	if rf, ok := ret.Get(0).(func(int, *carts.Cart) *carts.Cart); ok {
		r0 = rf(userID, cart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carts.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *carts.Cart) error); ok {
		r1 = rf(userID, cart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
