// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	collections "gofilm/bussinesses/collections"

	mock "github.com/stretchr/testify/mock"
)

// CollectionUseCase is an autogenerated mock type for the CollectionUseCase type
type CollectionUseCase struct {
	mock.Mock
}

// GetCollection provides a mock function with given fields: userID
func (_m *CollectionUseCase) GetCollection(userID int) (*collections.Collection, error) {
	ret := _m.Called(userID)

	var r0 *collections.Collection
	if rf, ok := ret.Get(0).(func(int) *collections.Collection); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collections.Collection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreCollection provides a mock function with given fields: userID
func (_m *CollectionUseCase) StoreCollection(userID int) (*collections.Collection, error) {
	ret := _m.Called(userID)

	var r0 *collections.Collection
	if rf, ok := ret.Get(0).(func(int) *collections.Collection); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collections.Collection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
