// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payments "gofilm/bussinesses/payments"

	mock "github.com/stretchr/testify/mock"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// ChangeStatus provides a mock function with given fields: payment
func (_m *PaymentRepository) ChangeStatus(payment *payments.Payment) (*payments.Payment, error) {
	ret := _m.Called(payment)

	var r0 *payments.Payment
	if rf, ok := ret.Get(0).(func(*payments.Payment) *payments.Payment); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payments.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*payments.Payment) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
