// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	films "gofilm/bussinesses/films"

	mock "github.com/stretchr/testify/mock"
)

// FilmFromAPI is an autogenerated mock type for the FilmFromAPI type
type FilmFromAPI struct {
	mock.Mock
}

// GetFilmFromAPI provides a mock function with given fields:
func (_m *FilmFromAPI) GetFilmFromAPI() []films.Convert {
	ret := _m.Called()

	var r0 []films.Convert
	if rf, ok := ret.Get(0).(func() []films.Convert); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]films.Convert)
		}
	}

	return r0
}
