// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	languages "gofilm/bussinesses/languages"

	mock "github.com/stretchr/testify/mock"
)

// LangRepository is an autogenerated mock type for the LangRepository type
type LangRepository struct {
	mock.Mock
}

// GetLang provides a mock function with given fields:
func (_m *LangRepository) GetLang() (*[]languages.Language, error) {
	ret := _m.Called()

	var r0 *[]languages.Language
	if rf, ok := ret.Get(0).(func() *[]languages.Language); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]languages.Language)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreLang provides a mock function with given fields: lang
func (_m *LangRepository) StoreLang(lang *languages.Language) (*languages.Language, error) {
	ret := _m.Called(lang)

	var r0 *languages.Language
	if rf, ok := ret.Get(0).(func(*languages.Language) *languages.Language); ok {
		r0 = rf(lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*languages.Language)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*languages.Language) error); ok {
		r1 = rf(lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
