// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	languages "gofilm/bussinesses/languages"

	mock "github.com/stretchr/testify/mock"
)

// LangUseCase is an autogenerated mock type for the LangUseCase type
type LangUseCase struct {
	mock.Mock
}

// GetLangs provides a mock function with given fields:
func (_m *LangUseCase) GetLangs() (*[]languages.Language, error) {
	ret := _m.Called()

	var r0 *[]languages.Language
	if rf, ok := ret.Get(0).(func() *[]languages.Language); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]languages.Language)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
