// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	genres "gofilm/bussinesses/genres"

	mock "github.com/stretchr/testify/mock"
)

// GenreFromAPI is an autogenerated mock type for the GenreFromAPI type
type GenreFromAPI struct {
	mock.Mock
}

// GetGenreFromAPI provides a mock function with given fields:
func (_m *GenreFromAPI) GetGenreFromAPI() []genres.Genre {
	ret := _m.Called()

	var r0 []genres.Genre
	if rf, ok := ret.Get(0).(func() []genres.Genre); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]genres.Genre)
		}
	}

	return r0
}
